/***************************************************************************//**
* \file TINY_YOLO_V2_OBJECT_DETECTION_tflm_model_int8x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains TINY_YOLO_V2_OBJECT_DETECTION model data.
* Date: 2025-09-05 14:33:05.756246
*******************************************************************************
* \copyright
* Copyright 2025, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/

/*
ml-coretools 3.0.0.8656 based on TensorFlow 2.15.0 and ethos-u-vela 4.2.0
    ml-coretools-middleware-streaming 3.1.0.15301
    ml-coretools-tflm-qemu-images 3.1.0.15301
*/

#ifndef TINY_YOLO_V2_OBJECT_DETECTION_TFLM_MODEL_INT8X8_H
#define TINY_YOLO_V2_OBJECT_DETECTION_TFLM_MODEL_INT8X8_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t TINY_YOLO_V2_OBJECT_DETECTION_model_bin[];
#else
extern uint8_t TINY_YOLO_V2_OBJECT_DETECTION_model_bin[];
#endif // CY_ML_MODEL_MEM
#define TINY_YOLO_V2_OBJECT_DETECTION_MODEL_BIN_LEN (1699216u)
#define TINY_YOLO_V2_OBJECT_DETECTION_ARENA_SIZE (234496u)

#endif // TINY_YOLO_V2_OBJECT_DETECTION_TFLM_MODEL_INT8X8_H

