/***************************************************************************//**
* \file YOLOV8N_PERSON_DETECTION_tflm_model_int8x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains YOLOV8N_PERSON_DETECTION model data.
* Date: 2025-08-20 16:05:16.001812
*******************************************************************************
* \copyright
* Copyright 2025, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/

/*
ml-coretools 3.0.0.8656 based on TensorFlow 2.15.0 and ethos-u-vela 4.2.0
    ml-coretools-middleware-streaming 3.1.0.15301
    ml-coretools-tflm-qemu-images 3.1.0.15301
*/

#ifndef YOLOV8N_PERSON_DETECTION_TFLM_MODEL_INT8X8_H
#define YOLOV8N_PERSON_DETECTION_TFLM_MODEL_INT8X8_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t YOLOV8N_PERSON_DETECTION_model_bin[];
#else
extern uint8_t YOLOV8N_PERSON_DETECTION_model_bin[];
#endif // CY_ML_MODEL_MEM
#define YOLOV8N_PERSON_DETECTION_MODEL_BIN_LEN (2194352u)
#define YOLOV8N_PERSON_DETECTION_ARENA_SIZE (5156864u)

#endif // YOLOV8N_PERSON_DETECTION_TFLM_MODEL_INT8X8_H

