/***************************************************************************//**
* \file ARCFACE_FACE_RECOGNITION_tflm_model_float.h
*
* \brief
* Autogenerated with ml-coretools, this file contains ARCFACE_FACE_RECOGNITION model data.
* Date: 2025-10-06 13:22:21.975236
*******************************************************************************
* \copyright
* Copyright 2025, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/

/*
ml-coretools 3.0.0.8948 based on TensorFlow 2.19.0 and ethos-u-vela 4.3.0
    ml-coretools-middleware-streaming 3.1.0.15478
    ml-coretools-tflm-qemu-images 3.1.0.15478
*/

#ifndef ARCFACE_FACE_RECOGNITION_TFLM_MODEL_FLOAT_H
#define ARCFACE_FACE_RECOGNITION_TFLM_MODEL_FLOAT_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t ARCFACE_FACE_RECOGNITION_model_bin[];
#else
extern uint8_t ARCFACE_FACE_RECOGNITION_model_bin[];
#endif // CY_ML_MODEL_MEM
#define ARCFACE_FACE_RECOGNITION_MODEL_BIN_LEN (28089984u)
#define ARCFACE_FACE_RECOGNITION_ARENA_SIZE (3469312u)

#endif // ARCFACE_FACE_RECOGNITION_TFLM_MODEL_FLOAT_H

