/***************************************************************************//**
* \file DEEPLAB_V3_MOBILENETV3_SEGMENTATION_tflm_model_int8x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains DEEPLAB_V3_MOBILENETV3_SEGMENTATION model data.
* Date: 2025-10-06 15:01:14.312951
*******************************************************************************
* \copyright
* Copyright 2025, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/

/*
ml-coretools 3.0.0.8948 based on TensorFlow 2.19.0 and ethos-u-vela 4.3.0
    ml-coretools-middleware-streaming 3.1.0.15478
    ml-coretools-tflm-qemu-images 3.1.0.15478
*/

#ifndef DEEPLAB_V3_MOBILENETV3_SEGMENTATION_TFLM_MODEL_INT8X8_H
#define DEEPLAB_V3_MOBILENETV3_SEGMENTATION_TFLM_MODEL_INT8X8_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t DEEPLAB_V3_MOBILENETV3_SEGMENTATION_model_bin[];
#else
extern uint8_t DEEPLAB_V3_MOBILENETV3_SEGMENTATION_model_bin[];
#endif // CY_ML_MODEL_MEM
#define DEEPLAB_V3_MOBILENETV3_SEGMENTATION_MODEL_BIN_LEN (201728u)
#define DEEPLAB_V3_MOBILENETV3_SEGMENTATION_ARENA_SIZE (850944u)

#endif // DEEPLAB_V3_MOBILENETV3_SEGMENTATION_TFLM_MODEL_INT8X8_H

