/***************************************************************************//**
* \file MOVENET_LIGHTNING_POSE_ESTIMATION_tflm_model_float.h
*
* \brief
* Autogenerated with ml-coretools, this file contains MOVENET_LIGHTNING_POSE_ESTIMATION model data.
* Date: 2025-08-19 15:29:25.044402
*******************************************************************************
* \copyright
* Copyright 2025, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/

/*
ml-coretools 3.0.0.8656 based on TensorFlow 2.15.0 and ethos-u-vela 4.2.0
    ml-coretools-middleware-streaming 3.1.0.15301
    ml-coretools-tflm-qemu-images 3.1.0.15301
*/

#ifndef MOVENET_LIGHTNING_POSE_ESTIMATION_TFLM_MODEL_FLOAT_H
#define MOVENET_LIGHTNING_POSE_ESTIMATION_TFLM_MODEL_FLOAT_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t MOVENET_LIGHTNING_POSE_ESTIMATION_model_bin[];
#else
extern uint8_t MOVENET_LIGHTNING_POSE_ESTIMATION_model_bin[];
#endif 
#define MOVENET_LIGHTNING_POSE_ESTIMATION_MODEL_BIN_LEN (2518880u)
#define MOVENET_LIGHTNING_POSE_ESTIMATION_ARENA_SIZE (1142784u)

#endif 

