/***************************************************************************//**
* \file HAND_LANDMARKS_POSE_ESTIMATION_tflm_model_float.h
*
* \brief
* Autogenerated with ml-coretools, this file contains HAND_LANDMARKS_POSE_ESTIMATION model data.
* Date: 2025-09-29 17:43:39.244319
*******************************************************************************
* \copyright
* Copyright 2025, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/

/*
ml-coretools 3.0.0.8656 based on TensorFlow 2.15.0 and ethos-u-vela 4.2.0
    ml-coretools-middleware-streaming 3.1.0.15301
    ml-coretools-tflm-qemu-images 3.1.0.15301
*/

#ifndef HAND_LANDMARKS_POSE_ESTIMATION_TFLM_MODEL_FLOAT_H
#define HAND_LANDMARKS_POSE_ESTIMATION_TFLM_MODEL_FLOAT_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t HAND_LANDMARKS_POSE_ESTIMATION_model_bin[];
#else
extern uint8_t HAND_LANDMARKS_POSE_ESTIMATION_model_bin[];
#endif // CY_ML_MODEL_MEM
#define HAND_LANDMARKS_POSE_ESTIMATION_MODEL_BIN_LEN (2454416u)
#define HAND_LANDMARKS_POSE_ESTIMATION_ARENA_SIZE (1144832u)

#endif // HAND_LANDMARKS_POSE_ESTIMATION_TFLM_MODEL_FLOAT_H

