/***************************************************************************//**
* \file SSD_MOBILENET_V1_PERSON_DETECTION_tflm_model_int8x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains SSD_MOBILENET_V1_PERSON_DETECTION model data.
* Date: 2025-09-17 16:05:41.683977
*******************************************************************************
* \copyright
* Copyright 2025, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/

/*
ml-coretools 3.0.0.8656 based on TensorFlow 2.15.0 and ethos-u-vela 4.2.0
    ml-coretools-middleware-streaming 3.1.0.15301
    ml-coretools-tflm-qemu-images 3.1.0.15301
*/

#ifndef SSD_MOBILENET_V1_PERSON_DETECTION_TFLM_MODEL_INT8X8_H
#define SSD_MOBILENET_V1_PERSON_DETECTION_TFLM_MODEL_INT8X8_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t SSD_MOBILENET_V1_PERSON_DETECTION_model_bin[];
#else
extern uint8_t SSD_MOBILENET_V1_PERSON_DETECTION_model_bin[];
#endif // CY_ML_MODEL_MEM
#define SSD_MOBILENET_V1_PERSON_DETECTION_MODEL_BIN_LEN (1694128u)
#define SSD_MOBILENET_V1_PERSON_DETECTION_ARENA_SIZE (289792u)

#endif // SSD_MOBILENET_V1_PERSON_DETECTION_TFLM_MODEL_INT8X8_H

