/***************************************************************************//**
* \file RESNET50_V2_FOOD_CLASSIFICATION_tflm_model_int8x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains RESNET50_V2_FOOD_CLASSIFICATION model data.
* Date: 2025-10-03 19:46:13.290935
*******************************************************************************
* \copyright
* Copyright 2025, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/

/*
ml-coretools 3.0.0.8948 based on TensorFlow 2.19.0 and ethos-u-vela 4.3.0
    ml-coretools-middleware-streaming 3.1.0.15478
    ml-coretools-tflm-qemu-images 3.1.0.15478
*/

#ifndef RESNET50_V2_FOOD_CLASSIFICATION_TFLM_MODEL_INT8X8_H
#define RESNET50_V2_FOOD_CLASSIFICATION_TFLM_MODEL_INT8X8_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t RESNET50_V2_FOOD_CLASSIFICATION_model_bin[];
#else
extern uint8_t RESNET50_V2_FOOD_CLASSIFICATION_model_bin[];
#endif // CY_ML_MODEL_MEM
#define RESNET50_V2_FOOD_CLASSIFICATION_MODEL_BIN_LEN (21888624u)
#define RESNET50_V2_FOOD_CLASSIFICATION_ARENA_SIZE (1951744u)

#endif // RESNET50_V2_FOOD_CLASSIFICATION_TFLM_MODEL_INT8X8_H

