/***************************************************************************//**
* \file MOBILENET_PLANT_LEAF_DISEASE_CLASSIFICATION_tflm_model_float.h
*
* \brief
* Autogenerated with ml-coretools, this file contains MOBILENET_PLANT_LEAF_DISEASE_CLASSIFICATION model data.
* Date: 2025-09-02 09:24:28.404271
*******************************************************************************
* \copyright
* Copyright 2025, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/

/*
ml-coretools 3.0.0.8656 based on TensorFlow 2.15.0 and ethos-u-vela 4.2.0
    ml-coretools-middleware-streaming 3.1.0.15301
    ml-coretools-tflm-qemu-images 3.1.0.15301
*/

#ifndef MOBILENET_PLANT_LEAF_DISEASE_CLASSIFICATION_TFLM_MODEL_FLOAT_H
#define MOBILENET_PLANT_LEAF_DISEASE_CLASSIFICATION_TFLM_MODEL_FLOAT_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t MOBILENET_PLANT_LEAF_DISEASE_CLASSIFICATION_model_bin[];
#else
extern uint8_t MOBILENET_PLANT_LEAF_DISEASE_CLASSIFICATION_model_bin[];
#endif // CY_ML_MODEL_MEM
#define MOBILENET_PLANT_LEAF_DISEASE_CLASSIFICATION_MODEL_BIN_LEN (2474176u)
#define MOBILENET_PLANT_LEAF_DISEASE_CLASSIFICATION_ARENA_SIZE (868352u)

#endif // MOBILENET_PLANT_LEAF_DISEASE_CLASSIFICATION_TFLM_MODEL_FLOAT_H

